// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZombieDefenseSystem.Infrastructure.Persistence;

#nullable disable

namespace ZombieDefenseSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ZombieDefenseSystem.Domain.Entities.EliminatedZombie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEliminados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosObtenidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZombieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionId");

                    b.HasIndex("ZombieId");

                    b.ToTable("Eliminados", (string)null);
                });

            modelBuilder.Entity("ZombieDefenseSystem.Domain.Entities.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalasDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalasUsadas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoUsado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalZombiesEliminados")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Simulaciones", (string)null);
                });

            modelBuilder.Entity("ZombieDefenseSystem.Domain.Entities.Zombie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("BalasNecesarias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelAmenaza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntajeBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoDisparo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zombies", (string)null);
                });

            modelBuilder.Entity("ZombieDefenseSystem.Domain.Entities.EliminatedZombie", b =>
                {
                    b.HasOne("ZombieDefenseSystem.Domain.Entities.Simulation", "Simulacion")
                        .WithMany("Eliminados")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieDefenseSystem.Domain.Entities.Zombie", "Zombie")
                        .WithMany()
                        .HasForeignKey("ZombieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Simulacion");

                    b.Navigation("Zombie");
                });

            modelBuilder.Entity("ZombieDefenseSystem.Domain.Entities.Simulation", b =>
                {
                    b.Navigation("Eliminados");
                });
#pragma warning restore 612, 618
        }
    }
}
